In [8]:
import pandas as pd

In [9]:
import numpy as np

## Leer datos

In [10]:
df = pd.read_excel("Precios Brendt 2024-10.xls",sheet_name='Datos a Utilizar')

In [11]:
df = df.drop(df.index[0])

In [12]:
df.columns = ['Dia', 'Precio']

## Retornos logaritmicos

In [13]:
df['Retornos logaritmicos'] = np.log(df['Precio'] / df['Precio'].shift(1))

In [23]:
df

            Dia  Precio  Retornos logaritmicos
1    2014-01-29  108.83                    NaN
2    2014-01-30  109.36               0.004858
3    2014-01-31  108.16              -0.011034
4    2014-02-03  106.55              -0.014997
5    2014-02-04  107.04               0.004588
6    2014-02-05  106.81              -0.002151
7    2014-02-06  108.15               0.012468
8    2014-02-07  110.12               0.018052
9    2014-02-10  110.18               0.000545
10   2014-02-11  109.21              -0.008843
11   2014-02-12  108.62              -0.005417
12   2014-02-13  108.98               0.003309
13   2014-02-14  108.63              -0.003217
14   2014-02-18  110.14               0.013805
15   2014-02-19  110.37               0.002086
16   2014-02-20  109.42              -0.008645
17   2014-02-21  109.03              -0.003571
18   2014-02-24  109.76               0.006673
19   2014-02-25  109.19              -0.005207
20   2014-02-26  109.39               0.001830
21   2014-02-27  108.54              -0.007801
22   2014-02-28  108.98               0.004046
23   2014-03-03  111.26               0.020705
24   2014-03-04  109.17              -0.018964
25   2014-03-05  108.15              -0.009387
26   2014-03-06  107.99              -0.001481
27   2014-03-07  109.14               0.010593
28   2014-03-10  108.27              -0.008003
29   2014-03-11  108.35               0.000739
30   2014-03-12  107.88              -0.004347
...         ...     ...                    ...
2512 2023-12-14   77.05               0.038499
2513 2023-12-15   76.84              -0.002729
2514 2023-12-18   78.89               0.026329
2515 2023-12-19   79.82               0.011720
2516 2023-12-20   81.10               0.015909
2517 2023-12-21   80.73              -0.004573
2518 2023-12-22   80.23              -0.006213
2519 2023-12-27   80.97               0.009181
2520 2023-12-28   79.04              -0.024125
2521 2023-12-29   77.69              -0.017228
2522 2024-01-02   76.24              -0.018840
2523 2024-01-03   77.18               0.012254
2524 2024-01-04   75.79              -0.018174
2525 2024-01-05   78.31               0.032709
2526 2024-01-08   75.47              -0.036940
2527 2024-01-09   77.97               0.032589
2528 2024-01-10   78.46               0.006265
2529 2024-01-11   80.21               0.022059
2530 2024-01-12   79.89              -0.003998
2531 2024-01-15   79.76              -0.001629
2532 2024-01-16   80.15               0.004878
2533 2024-01-17   78.88              -0.015972
2534 2024-01-18   81.04               0.027015
2535 2024-01-19   80.71              -0.004080
2536 2024-01-22   81.70               0.012192
2537 2024-01-23   82.04               0.004153
2538 2024-01-24   82.15               0.001340
2539 2024-01-25   82.33               0.002189
2540 2024-01-26   83.34               0.012193
2541 2024-01-29   83.99               0.007769

[2541 rows x 3 columns]

## Media diaria

In [25]:
media_diaria = df['Retornos logaritmicos'].mean()

In [28]:
media_diaria

-0.00010200365652379218

## Volatilidad diaria

In [29]:
volatilidad_diaria = df['Retornos logaritmicos'].std()

In [30]:
volatilidad_diaria

0.031101540033155576

## Movimiento browniano geometrico
$
S_t = S_{t-1}e^{r+\sigma \epsilon_t}
$

In [33]:
np.random.normal()

0.22809707505179866